### PR TITLE
Issue/222 httprequest cleanup

### PR DESCRIPTION
**Pull request by valllllll2000**
Remove unused methods from class

### CODE REVIEW

**Comment by punchagan** [comment]
Thanks for working on this, @valllllll2000 !

**Comment by punchagan** [comment]
I'm not familiar with this code. Could you explain how you found the code that was not being used? How do you recommend that a review for this should be done? :thinking:

**Comment by valllllll2000** [comment]
@punchagan my IDE detected unused code so I just went on and removed all the methods and vars that were not used in our code. I ran the app on the emulator and all worked. You can also check the tests that ave been run successfully and the build succeeds so I think it's all good, not sure what else you can check. I do not think it is worth doing a release with these changes as it should not really bring any value for the app.

**Comment by punchagan** [comment]
Thanks for the explanation, @valllllll2000! Merging! I agree, there's limited value in doing a release with these changes.

**Pull request merged**
